import { NavBarFilter } from "@/components/NavBarFilter";
import { InputSearch } from "@/components/InputSearch";
import { CardPost } from "@/components/CardPost";
import { Header } from "@/components/Header";
import Head from "next/head";
import Image from "next/image";
import { ButtonContact } from "@/components/ButtonContact";

export default function Home() {
  return (
    <>
      <Head>
        <title>B. LIVE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="w-full max-w-[1200px] flex flex-col mx-auto pb-12">
      <div className="flex items-center justify-center">
          <Header />
          <ButtonContact />
        </div>
        <InputSearch />
        <NavBarFilter />
        <div className="flex items-center justify-center w-full h-full gap-8 mt-12 mb-12">
          <div className="flex flex-1 h-[334px] relative rounded-2xl overflow-hidden">
            <Image
              src="https://images.prismic.io/launchdarkly/6bfcaa10-40a3-42a5-9346-9e83d25cbeb4_What's%20So%20Great%20About%20Next.js.png?ixlib=gatsbyFP&auto=compress%2Cformat&fit=max"
              alt="Image post test"
              fill={true}
              style={{ objectFit: "cover" }}
            />
          </div>
          <div className="flex flex-1 h-[334px] flex-col gap-6">
            <h1 className="font-bold text-[40px] text-gray-700">
              Como desenvolver um Blog com Next.js
            </h1>
            <p className="text-gray-600">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Saepe
              dolorem minima quo mollitia soluta exercitationem optio sed,
              reprehenderit tenetur velit nisi ea rerum dolor ipsam,
              voluptatibus assumenda aliquid quo mollitia soluta exercitationem
              optio sed, reprehenderit tenetur velit nisi ea rerum dolor ipsam,
              voluptatibus assumenda ali nostrum porro!, ipsam, voluptatibus
              assumenda aliquid nostrum porro!
            </p>
            <div>
              <p className="font-bold text-[#2DC0B6]">Adailton Cazé</p>
              <p className="text-sm text-gray-500">31 de janeiro de 2023</p>
            </div>
          </div>
        </div>
        <div className="grid grid-cols-3 gap-8 mt-12">
          <CardPost />
          <CardPost />
          <CardPost />
          <CardPost />
          <CardPost />
          <CardPost />
          <CardPost />
          <CardPost />
          <CardPost />
        </div>
      </div>
    </>
  );
}
